# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class AcknowledgeClaimRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, claim_id: str=None, participant: AllOfAcknowledgeClaimRequestParticipant=None):  # noqa: E501
        """AcknowledgeClaimRequest - a model defined in Swagger

        :param signature: The signature of this AcknowledgeClaimRequest.  # noqa: E501
        :type signature: object
        :param claim_id: The claim_id of this AcknowledgeClaimRequest.  # noqa: E501
        :type claim_id: str
        :param participant: The participant of this AcknowledgeClaimRequest.  # noqa: E501
        :type participant: AllOfAcknowledgeClaimRequestParticipant
        """
        self.swagger_types = {
            'signature': object,
            'claim_id': str,
            'participant': AllOfAcknowledgeClaimRequestParticipant
        }

        self.attribute_map = {
            'signature': 'Signature',
            'claim_id': 'ClaimId',
            'participant': 'Participant'
        }
        self._signature = signature
        self._claim_id = claim_id
        self._participant = participant

    @classmethod
    def from_dict(cls, dikt) -> 'AcknowledgeClaimRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AcknowledgeClaimRequest of this AcknowledgeClaimRequest.  # noqa: E501
        :rtype: AcknowledgeClaimRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this AcknowledgeClaimRequest.


        :return: The signature of this AcknowledgeClaimRequest.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this AcknowledgeClaimRequest.


        :param signature: The signature of this AcknowledgeClaimRequest.
        :type signature: object
        """

        self._signature = signature

    @property
    def claim_id(self) -> str:
        """Gets the claim_id of this AcknowledgeClaimRequest.


        :return: The claim_id of this AcknowledgeClaimRequest.
        :rtype: str
        """
        return self._claim_id

    @claim_id.setter
    def claim_id(self, claim_id: str):
        """Sets the claim_id of this AcknowledgeClaimRequest.


        :param claim_id: The claim_id of this AcknowledgeClaimRequest.
        :type claim_id: str
        """
        if claim_id is None:
            raise ValueError("Invalid value for `claim_id`, must not be `None`")  # noqa: E501

        self._claim_id = claim_id

    @property
    def participant(self) -> AllOfAcknowledgeClaimRequestParticipant:
        """Gets the participant of this AcknowledgeClaimRequest.


        :return: The participant of this AcknowledgeClaimRequest.
        :rtype: AllOfAcknowledgeClaimRequestParticipant
        """
        return self._participant

    @participant.setter
    def participant(self, participant: AllOfAcknowledgeClaimRequestParticipant):
        """Sets the participant of this AcknowledgeClaimRequest.


        :param participant: The participant of this AcknowledgeClaimRequest.
        :type participant: AllOfAcknowledgeClaimRequestParticipant
        """
        if participant is None:
            raise ValueError("Invalid value for `participant`, must not be `None`")  # noqa: E501

        self._participant = participant
