# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ClaimOperationReason(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    USER_REQUESTED = "USER_REQUESTED"
    ACCOUNT_CLOSURE = "ACCOUNT_CLOSURE"
    FRAUD = "FRAUD"
    DEFAULT_OPERATION = "DEFAULT_OPERATION"
    def __init__(self):  # noqa: E501
        """ClaimOperationReason - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ClaimOperationReason':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ClaimOperationReason of this ClaimOperationReason.  # noqa: E501
        :rtype: ClaimOperationReason
        """
        return util.deserialize_model(dikt, cls)
