# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.extended_disputeall_of1properties_resolution import ExtendedDisputeallOf1propertiesResolution  # noqa: F401,E501
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class CloseDisputeRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, dispute_id: str=None, participant: AllOfCloseDisputeRequestParticipant=None, resolution: ExtendedDisputeallOf1propertiesResolution=None):  # noqa: E501
        """CloseDisputeRequest - a model defined in Swagger

        :param signature: The signature of this CloseDisputeRequest.  # noqa: E501
        :type signature: object
        :param dispute_id: The dispute_id of this CloseDisputeRequest.  # noqa: E501
        :type dispute_id: str
        :param participant: The participant of this CloseDisputeRequest.  # noqa: E501
        :type participant: AllOfCloseDisputeRequestParticipant
        :param resolution: The resolution of this CloseDisputeRequest.  # noqa: E501
        :type resolution: ExtendedDisputeallOf1propertiesResolution
        """
        self.swagger_types = {
            'signature': object,
            'dispute_id': str,
            'participant': AllOfCloseDisputeRequestParticipant,
            'resolution': ExtendedDisputeallOf1propertiesResolution
        }

        self.attribute_map = {
            'signature': 'Signature',
            'dispute_id': 'DisputeId',
            'participant': 'Participant',
            'resolution': 'Resolution'
        }
        self._signature = signature
        self._dispute_id = dispute_id
        self._participant = participant
        self._resolution = resolution

    @classmethod
    def from_dict(cls, dikt) -> 'CloseDisputeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CloseDisputeRequest of this CloseDisputeRequest.  # noqa: E501
        :rtype: CloseDisputeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this CloseDisputeRequest.


        :return: The signature of this CloseDisputeRequest.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this CloseDisputeRequest.


        :param signature: The signature of this CloseDisputeRequest.
        :type signature: object
        """

        self._signature = signature

    @property
    def dispute_id(self) -> str:
        """Gets the dispute_id of this CloseDisputeRequest.

        ID da disputa  # noqa: E501

        :return: The dispute_id of this CloseDisputeRequest.
        :rtype: str
        """
        return self._dispute_id

    @dispute_id.setter
    def dispute_id(self, dispute_id: str):
        """Sets the dispute_id of this CloseDisputeRequest.

        ID da disputa  # noqa: E501

        :param dispute_id: The dispute_id of this CloseDisputeRequest.
        :type dispute_id: str
        """

        self._dispute_id = dispute_id

    @property
    def participant(self) -> AllOfCloseDisputeRequestParticipant:
        """Gets the participant of this CloseDisputeRequest.


        :return: The participant of this CloseDisputeRequest.
        :rtype: AllOfCloseDisputeRequestParticipant
        """
        return self._participant

    @participant.setter
    def participant(self, participant: AllOfCloseDisputeRequestParticipant):
        """Sets the participant of this CloseDisputeRequest.


        :param participant: The participant of this CloseDisputeRequest.
        :type participant: AllOfCloseDisputeRequestParticipant
        """

        self._participant = participant

    @property
    def resolution(self) -> ExtendedDisputeallOf1propertiesResolution:
        """Gets the resolution of this CloseDisputeRequest.


        :return: The resolution of this CloseDisputeRequest.
        :rtype: ExtendedDisputeallOf1propertiesResolution
        """
        return self._resolution

    @resolution.setter
    def resolution(self, resolution: ExtendedDisputeallOf1propertiesResolution):
        """Sets the resolution of this CloseDisputeRequest.


        :param resolution: The resolution of this CloseDisputeRequest.
        :type resolution: ExtendedDisputeallOf1propertiesResolution
        """

        self._resolution = resolution
