# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.create_dispute_responseproperties_dispute import CreateDisputeResponsepropertiesDispute  # noqa: F401,E501
from swagger_server import util


class CloseDisputeResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, dispute: CreateDisputeResponsepropertiesDispute=None):  # noqa: E501
        """CloseDisputeResponse - a model defined in Swagger

        :param signature: The signature of this CloseDisputeResponse.  # noqa: E501
        :type signature: object
        :param dispute: The dispute of this CloseDisputeResponse.  # noqa: E501
        :type dispute: CreateDisputeResponsepropertiesDispute
        """
        self.swagger_types = {
            'signature': object,
            'dispute': CreateDisputeResponsepropertiesDispute
        }

        self.attribute_map = {
            'signature': 'Signature',
            'dispute': 'Dispute'
        }
        self._signature = signature
        self._dispute = dispute

    @classmethod
    def from_dict(cls, dikt) -> 'CloseDisputeResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CloseDisputeResponse of this CloseDisputeResponse.  # noqa: E501
        :rtype: CloseDisputeResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this CloseDisputeResponse.


        :return: The signature of this CloseDisputeResponse.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this CloseDisputeResponse.


        :param signature: The signature of this CloseDisputeResponse.
        :type signature: object
        """

        self._signature = signature

    @property
    def dispute(self) -> CreateDisputeResponsepropertiesDispute:
        """Gets the dispute of this CloseDisputeResponse.


        :return: The dispute of this CloseDisputeResponse.
        :rtype: CreateDisputeResponsepropertiesDispute
        """
        return self._dispute

    @dispute.setter
    def dispute(self, dispute: CreateDisputeResponsepropertiesDispute):
        """Sets the dispute of this CloseDisputeResponse.


        :param dispute: The dispute of this CloseDisputeResponse.
        :type dispute: CreateDisputeResponsepropertiesDispute
        """

        self._dispute = dispute
