# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class CompleteClaimRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, claim_id: str=None, participant: AllOfCompleteClaimRequestParticipant=None, request_id: str=None):  # noqa: E501
        """CompleteClaimRequest - a model defined in Swagger

        :param signature: The signature of this CompleteClaimRequest.  # noqa: E501
        :type signature: object
        :param claim_id: The claim_id of this CompleteClaimRequest.  # noqa: E501
        :type claim_id: str
        :param participant: The participant of this CompleteClaimRequest.  # noqa: E501
        :type participant: AllOfCompleteClaimRequestParticipant
        :param request_id: The request_id of this CompleteClaimRequest.  # noqa: E501
        :type request_id: str
        """
        self.swagger_types = {
            'signature': object,
            'claim_id': str,
            'participant': AllOfCompleteClaimRequestParticipant,
            'request_id': str
        }

        self.attribute_map = {
            'signature': 'Signature',
            'claim_id': 'ClaimId',
            'participant': 'Participant',
            'request_id': 'RequestId'
        }
        self._signature = signature
        self._claim_id = claim_id
        self._participant = participant
        self._request_id = request_id

    @classmethod
    def from_dict(cls, dikt) -> 'CompleteClaimRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CompleteClaimRequest of this CompleteClaimRequest.  # noqa: E501
        :rtype: CompleteClaimRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this CompleteClaimRequest.


        :return: The signature of this CompleteClaimRequest.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this CompleteClaimRequest.


        :param signature: The signature of this CompleteClaimRequest.
        :type signature: object
        """

        self._signature = signature

    @property
    def claim_id(self) -> str:
        """Gets the claim_id of this CompleteClaimRequest.


        :return: The claim_id of this CompleteClaimRequest.
        :rtype: str
        """
        return self._claim_id

    @claim_id.setter
    def claim_id(self, claim_id: str):
        """Sets the claim_id of this CompleteClaimRequest.


        :param claim_id: The claim_id of this CompleteClaimRequest.
        :type claim_id: str
        """
        if claim_id is None:
            raise ValueError("Invalid value for `claim_id`, must not be `None`")  # noqa: E501

        self._claim_id = claim_id

    @property
    def participant(self) -> AllOfCompleteClaimRequestParticipant:
        """Gets the participant of this CompleteClaimRequest.


        :return: The participant of this CompleteClaimRequest.
        :rtype: AllOfCompleteClaimRequestParticipant
        """
        return self._participant

    @participant.setter
    def participant(self, participant: AllOfCompleteClaimRequestParticipant):
        """Sets the participant of this CompleteClaimRequest.


        :param participant: The participant of this CompleteClaimRequest.
        :type participant: AllOfCompleteClaimRequestParticipant
        """
        if participant is None:
            raise ValueError("Invalid value for `participant`, must not be `None`")  # noqa: E501

        self._participant = participant

    @property
    def request_id(self) -> str:
        """Gets the request_id of this CompleteClaimRequest.

        Chave de idempotência da requisição. UUID versão 4.  # noqa: E501

        :return: The request_id of this CompleteClaimRequest.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id: str):
        """Sets the request_id of this CompleteClaimRequest.

        Chave de idempotência da requisição. UUID versão 4.  # noqa: E501

        :param request_id: The request_id of this CompleteClaimRequest.
        :type request_id: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id
