# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class ConfirmClaimRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, claim_id: str=None, participant: AllOfConfirmClaimRequestParticipant=None, reason: str=None):  # noqa: E501
        """ConfirmClaimRequest - a model defined in Swagger

        :param signature: The signature of this ConfirmClaimRequest.  # noqa: E501
        :type signature: object
        :param claim_id: The claim_id of this ConfirmClaimRequest.  # noqa: E501
        :type claim_id: str
        :param participant: The participant of this ConfirmClaimRequest.  # noqa: E501
        :type participant: AllOfConfirmClaimRequestParticipant
        :param reason: The reason of this ConfirmClaimRequest.  # noqa: E501
        :type reason: str
        """
        self.swagger_types = {
            'signature': object,
            'claim_id': str,
            'participant': AllOfConfirmClaimRequestParticipant,
            'reason': str
        }

        self.attribute_map = {
            'signature': 'Signature',
            'claim_id': 'ClaimId',
            'participant': 'Participant',
            'reason': 'Reason'
        }
        self._signature = signature
        self._claim_id = claim_id
        self._participant = participant
        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'ConfirmClaimRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ConfirmClaimRequest of this ConfirmClaimRequest.  # noqa: E501
        :rtype: ConfirmClaimRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this ConfirmClaimRequest.


        :return: The signature of this ConfirmClaimRequest.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this ConfirmClaimRequest.


        :param signature: The signature of this ConfirmClaimRequest.
        :type signature: object
        """

        self._signature = signature

    @property
    def claim_id(self) -> str:
        """Gets the claim_id of this ConfirmClaimRequest.


        :return: The claim_id of this ConfirmClaimRequest.
        :rtype: str
        """
        return self._claim_id

    @claim_id.setter
    def claim_id(self, claim_id: str):
        """Sets the claim_id of this ConfirmClaimRequest.


        :param claim_id: The claim_id of this ConfirmClaimRequest.
        :type claim_id: str
        """
        if claim_id is None:
            raise ValueError("Invalid value for `claim_id`, must not be `None`")  # noqa: E501

        self._claim_id = claim_id

    @property
    def participant(self) -> AllOfConfirmClaimRequestParticipant:
        """Gets the participant of this ConfirmClaimRequest.


        :return: The participant of this ConfirmClaimRequest.
        :rtype: AllOfConfirmClaimRequestParticipant
        """
        return self._participant

    @participant.setter
    def participant(self, participant: AllOfConfirmClaimRequestParticipant):
        """Sets the participant of this ConfirmClaimRequest.


        :param participant: The participant of this ConfirmClaimRequest.
        :type participant: AllOfConfirmClaimRequestParticipant
        """
        if participant is None:
            raise ValueError("Invalid value for `participant`, must not be `None`")  # noqa: E501

        self._participant = participant

    @property
    def reason(self) -> str:
        """Gets the reason of this ConfirmClaimRequest.

        Razão da operação  # noqa: E501

        :return: The reason of this ConfirmClaimRequest.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this ConfirmClaimRequest.

        Razão da operação  # noqa: E501

        :param reason: The reason of this ConfirmClaimRequest.
        :type reason: str
        """
        allowed_values = ["USER_REQUESTED", "ACCOUNT_CLOSURE", "FRAUD", "DEFAULT_OPERATION"]  # noqa: E501
        if reason not in allowed_values:
            raise ValueError(
                "Invalid value for `reason` ({0}), must be one of {1}"
                .format(reason, allowed_values)
            )

        self._reason = reason
