# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_entry_by_cid_responseproperties_entry import GetEntryByCidResponsepropertiesEntry  # noqa: F401,E501
from swagger_server import util


class CreateEntryResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, entry: GetEntryByCidResponsepropertiesEntry=None):  # noqa: E501
        """CreateEntryResponse - a model defined in Swagger

        :param signature: The signature of this CreateEntryResponse.  # noqa: E501
        :type signature: object
        :param entry: The entry of this CreateEntryResponse.  # noqa: E501
        :type entry: GetEntryByCidResponsepropertiesEntry
        """
        self.swagger_types = {
            'signature': object,
            'entry': GetEntryByCidResponsepropertiesEntry
        }

        self.attribute_map = {
            'signature': 'Signature',
            'entry': 'Entry'
        }
        self._signature = signature
        self._entry = entry

    @classmethod
    def from_dict(cls, dikt) -> 'CreateEntryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateEntryResponse of this CreateEntryResponse.  # noqa: E501
        :rtype: CreateEntryResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this CreateEntryResponse.


        :return: The signature of this CreateEntryResponse.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this CreateEntryResponse.


        :param signature: The signature of this CreateEntryResponse.
        :type signature: object
        """

        self._signature = signature

    @property
    def entry(self) -> GetEntryByCidResponsepropertiesEntry:
        """Gets the entry of this CreateEntryResponse.


        :return: The entry of this CreateEntryResponse.
        :rtype: GetEntryByCidResponsepropertiesEntry
        """
        return self._entry

    @entry.setter
    def entry(self, entry: GetEntryByCidResponsepropertiesEntry):
        """Sets the entry of this CreateEntryResponse.


        :param entry: The entry of this CreateEntryResponse.
        :type entry: GetEntryByCidResponsepropertiesEntry
        """
        if entry is None:
            raise ValueError("Invalid value for `entry`, must not be `None`")  # noqa: E501

        self._entry = entry
