# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.extended_disputeall_of0 import ExtendedDisputeallOf0  # noqa: F401,E501
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class CreateDisputeRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, participant: AllOfCreateDisputeRequestParticipant=None, dispute: ExtendedDisputeallOf0=None):  # noqa: E501
        """CreateDisputeRequest - a model defined in Swagger

        :param signature: The signature of this CreateDisputeRequest.  # noqa: E501
        :type signature: object
        :param participant: The participant of this CreateDisputeRequest.  # noqa: E501
        :type participant: AllOfCreateDisputeRequestParticipant
        :param dispute: The dispute of this CreateDisputeRequest.  # noqa: E501
        :type dispute: ExtendedDisputeallOf0
        """
        self.swagger_types = {
            'signature': object,
            'participant': AllOfCreateDisputeRequestParticipant,
            'dispute': ExtendedDisputeallOf0
        }

        self.attribute_map = {
            'signature': 'Signature',
            'participant': 'Participant',
            'dispute': 'Dispute'
        }
        self._signature = signature
        self._participant = participant
        self._dispute = dispute

    @classmethod
    def from_dict(cls, dikt) -> 'CreateDisputeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateDisputeRequest of this CreateDisputeRequest.  # noqa: E501
        :rtype: CreateDisputeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this CreateDisputeRequest.


        :return: The signature of this CreateDisputeRequest.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this CreateDisputeRequest.


        :param signature: The signature of this CreateDisputeRequest.
        :type signature: object
        """

        self._signature = signature

    @property
    def participant(self) -> AllOfCreateDisputeRequestParticipant:
        """Gets the participant of this CreateDisputeRequest.


        :return: The participant of this CreateDisputeRequest.
        :rtype: AllOfCreateDisputeRequestParticipant
        """
        return self._participant

    @participant.setter
    def participant(self, participant: AllOfCreateDisputeRequestParticipant):
        """Sets the participant of this CreateDisputeRequest.


        :param participant: The participant of this CreateDisputeRequest.
        :type participant: AllOfCreateDisputeRequestParticipant
        """

        self._participant = participant

    @property
    def dispute(self) -> ExtendedDisputeallOf0:
        """Gets the dispute of this CreateDisputeRequest.


        :return: The dispute of this CreateDisputeRequest.
        :rtype: ExtendedDisputeallOf0
        """
        return self._dispute

    @dispute.setter
    def dispute(self, dispute: ExtendedDisputeallOf0):
        """Sets the dispute of this CreateDisputeRequest.


        :param dispute: The dispute of this CreateDisputeRequest.
        :type dispute: ExtendedDisputeallOf0
        """

        self._dispute = dispute
