# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class CreateDisputeResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, dispute: AllOfCreateDisputeResponseDispute=None):  # noqa: E501
        """CreateDisputeResponse - a model defined in Swagger

        :param signature: The signature of this CreateDisputeResponse.  # noqa: E501
        :type signature: object
        :param dispute: The dispute of this CreateDisputeResponse.  # noqa: E501
        :type dispute: AllOfCreateDisputeResponseDispute
        """
        self.swagger_types = {
            'signature': object,
            'dispute': AllOfCreateDisputeResponseDispute
        }

        self.attribute_map = {
            'signature': 'Signature',
            'dispute': 'Dispute'
        }
        self._signature = signature
        self._dispute = dispute

    @classmethod
    def from_dict(cls, dikt) -> 'CreateDisputeResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateDisputeResponse of this CreateDisputeResponse.  # noqa: E501
        :rtype: CreateDisputeResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this CreateDisputeResponse.


        :return: The signature of this CreateDisputeResponse.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this CreateDisputeResponse.


        :param signature: The signature of this CreateDisputeResponse.
        :type signature: object
        """

        self._signature = signature

    @property
    def dispute(self) -> AllOfCreateDisputeResponseDispute:
        """Gets the dispute of this CreateDisputeResponse.


        :return: The dispute of this CreateDisputeResponse.
        :rtype: AllOfCreateDisputeResponseDispute
        """
        return self._dispute

    @dispute.setter
    def dispute(self, dispute: AllOfCreateDisputeResponseDispute):
        """Sets the dispute of this CreateDisputeResponse.


        :param dispute: The dispute of this CreateDisputeResponse.
        :type dispute: AllOfCreateDisputeResponseDispute
        """

        self._dispute = dispute
