# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.extended_sync_verificationall_of0 import ExtendedSyncVerificationallOf0  # noqa: F401,E501
from swagger_server import util


class CreateSyncVerificationRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, sync_verification: ExtendedSyncVerificationallOf0=None):  # noqa: E501
        """CreateSyncVerificationRequest - a model defined in Swagger

        :param signature: The signature of this CreateSyncVerificationRequest.  # noqa: E501
        :type signature: object
        :param sync_verification: The sync_verification of this CreateSyncVerificationRequest.  # noqa: E501
        :type sync_verification: ExtendedSyncVerificationallOf0
        """
        self.swagger_types = {
            'signature': object,
            'sync_verification': ExtendedSyncVerificationallOf0
        }

        self.attribute_map = {
            'signature': 'Signature',
            'sync_verification': 'SyncVerification'
        }
        self._signature = signature
        self._sync_verification = sync_verification

    @classmethod
    def from_dict(cls, dikt) -> 'CreateSyncVerificationRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateSyncVerificationRequest of this CreateSyncVerificationRequest.  # noqa: E501
        :rtype: CreateSyncVerificationRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this CreateSyncVerificationRequest.


        :return: The signature of this CreateSyncVerificationRequest.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this CreateSyncVerificationRequest.


        :param signature: The signature of this CreateSyncVerificationRequest.
        :type signature: object
        """

        self._signature = signature

    @property
    def sync_verification(self) -> ExtendedSyncVerificationallOf0:
        """Gets the sync_verification of this CreateSyncVerificationRequest.


        :return: The sync_verification of this CreateSyncVerificationRequest.
        :rtype: ExtendedSyncVerificationallOf0
        """
        return self._sync_verification

    @sync_verification.setter
    def sync_verification(self, sync_verification: ExtendedSyncVerificationallOf0):
        """Sets the sync_verification of this CreateSyncVerificationRequest.


        :param sync_verification: The sync_verification of this CreateSyncVerificationRequest.
        :type sync_verification: ExtendedSyncVerificationallOf0
        """
        if sync_verification is None:
            raise ValueError("Invalid value for `sync_verification`, must not be `None`")  # noqa: E501

        self._sync_verification = sync_verification
