# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.entryproperties_key import EntrypropertiesKey  # noqa: F401,E501
from swagger_server.models.object import Object  # noqa: F401,E501
from swagger_server import util


class DeleteEntryRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, key: EntrypropertiesKey=None, participant: AllOfDeleteEntryRequestParticipant=None, reason: AllOfDeleteEntryRequestReason=None):  # noqa: E501
        """DeleteEntryRequest - a model defined in Swagger

        :param signature: The signature of this DeleteEntryRequest.  # noqa: E501
        :type signature: object
        :param key: The key of this DeleteEntryRequest.  # noqa: E501
        :type key: EntrypropertiesKey
        :param participant: The participant of this DeleteEntryRequest.  # noqa: E501
        :type participant: AllOfDeleteEntryRequestParticipant
        :param reason: The reason of this DeleteEntryRequest.  # noqa: E501
        :type reason: AllOfDeleteEntryRequestReason
        """
        self.swagger_types = {
            'signature': object,
            'key': EntrypropertiesKey,
            'participant': AllOfDeleteEntryRequestParticipant,
            'reason': AllOfDeleteEntryRequestReason
        }

        self.attribute_map = {
            'signature': 'Signature',
            'key': 'Key',
            'participant': 'Participant',
            'reason': 'Reason'
        }
        self._signature = signature
        self._key = key
        self._participant = participant
        self._reason = reason

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteEntryRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteEntryRequest of this DeleteEntryRequest.  # noqa: E501
        :rtype: DeleteEntryRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this DeleteEntryRequest.


        :return: The signature of this DeleteEntryRequest.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this DeleteEntryRequest.


        :param signature: The signature of this DeleteEntryRequest.
        :type signature: object
        """

        self._signature = signature

    @property
    def key(self) -> EntrypropertiesKey:
        """Gets the key of this DeleteEntryRequest.


        :return: The key of this DeleteEntryRequest.
        :rtype: EntrypropertiesKey
        """
        return self._key

    @key.setter
    def key(self, key: EntrypropertiesKey):
        """Sets the key of this DeleteEntryRequest.


        :param key: The key of this DeleteEntryRequest.
        :type key: EntrypropertiesKey
        """
        if key is None:
            raise ValueError("Invalid value for `key`, must not be `None`")  # noqa: E501

        self._key = key

    @property
    def participant(self) -> AllOfDeleteEntryRequestParticipant:
        """Gets the participant of this DeleteEntryRequest.


        :return: The participant of this DeleteEntryRequest.
        :rtype: AllOfDeleteEntryRequestParticipant
        """
        return self._participant

    @participant.setter
    def participant(self, participant: AllOfDeleteEntryRequestParticipant):
        """Sets the participant of this DeleteEntryRequest.


        :param participant: The participant of this DeleteEntryRequest.
        :type participant: AllOfDeleteEntryRequestParticipant
        """
        if participant is None:
            raise ValueError("Invalid value for `participant`, must not be `None`")  # noqa: E501

        self._participant = participant

    @property
    def reason(self) -> AllOfDeleteEntryRequestReason:
        """Gets the reason of this DeleteEntryRequest.


        :return: The reason of this DeleteEntryRequest.
        :rtype: AllOfDeleteEntryRequestReason
        """
        return self._reason

    @reason.setter
    def reason(self, reason: AllOfDeleteEntryRequestReason):
        """Sets the reason of this DeleteEntryRequest.


        :param reason: The reason of this DeleteEntryRequest.
        :type reason: AllOfDeleteEntryRequestReason
        """
        if reason is None:
            raise ValueError("Invalid value for `reason`, must not be `None`")  # noqa: E501

        self._reason = reason
