# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.entryproperties_key import EntrypropertiesKey  # noqa: F401,E501
from swagger_server import util


class DeleteEntryResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, key: EntrypropertiesKey=None):  # noqa: E501
        """DeleteEntryResponse - a model defined in Swagger

        :param signature: The signature of this DeleteEntryResponse.  # noqa: E501
        :type signature: object
        :param key: The key of this DeleteEntryResponse.  # noqa: E501
        :type key: EntrypropertiesKey
        """
        self.swagger_types = {
            'signature': object,
            'key': EntrypropertiesKey
        }

        self.attribute_map = {
            'signature': 'Signature',
            'key': 'Key'
        }
        self._signature = signature
        self._key = key

    @classmethod
    def from_dict(cls, dikt) -> 'DeleteEntryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeleteEntryResponse of this DeleteEntryResponse.  # noqa: E501
        :rtype: DeleteEntryResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this DeleteEntryResponse.


        :return: The signature of this DeleteEntryResponse.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this DeleteEntryResponse.


        :param signature: The signature of this DeleteEntryResponse.
        :type signature: object
        """

        self._signature = signature

    @property
    def key(self) -> EntrypropertiesKey:
        """Gets the key of this DeleteEntryResponse.


        :return: The key of this DeleteEntryResponse.
        :rtype: EntrypropertiesKey
        """
        return self._key

    @key.setter
    def key(self, key: EntrypropertiesKey):
        """Sets the key of this DeleteEntryResponse.


        :param key: The key of this DeleteEntryResponse.
        :type key: EntrypropertiesKey
        """
        if key is None:
            raise ValueError("Invalid value for `key`, must not be `None`")  # noqa: E501

        self._key = key
