# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EntryOperationReason(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    USER_REQUESTED = "USER_REQUESTED"
    ACCOUNT_CLOSURE = "ACCOUNT_CLOSURE"
    BRANCH_TRANSFER = "BRANCH_TRANSFER"
    ENTRY_INACTIVITY = "ENTRY_INACTIVITY"
    RECONCILIATION = "RECONCILIATION"
    FRAUD = "FRAUD"
    def __init__(self):  # noqa: E501
        """EntryOperationReason - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'EntryOperationReason':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EntryOperationReason of this EntryOperationReason.  # noqa: E501
        :rtype: EntryOperationReason
        """
        return util.deserialize_model(dikt, cls)
