# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.create_cid_set_file_responseproperties_cid_set_file import CreateCidSetFileResponsepropertiesCidSetFile  # noqa: F401,E501
from swagger_server import util


class GetCidSetFileResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, cid_set_file: CreateCidSetFileResponsepropertiesCidSetFile=None):  # noqa: E501
        """GetCidSetFileResponse - a model defined in Swagger

        :param signature: The signature of this GetCidSetFileResponse.  # noqa: E501
        :type signature: object
        :param cid_set_file: The cid_set_file of this GetCidSetFileResponse.  # noqa: E501
        :type cid_set_file: CreateCidSetFileResponsepropertiesCidSetFile
        """
        self.swagger_types = {
            'signature': object,
            'cid_set_file': CreateCidSetFileResponsepropertiesCidSetFile
        }

        self.attribute_map = {
            'signature': 'Signature',
            'cid_set_file': 'CidSetFile'
        }
        self._signature = signature
        self._cid_set_file = cid_set_file

    @classmethod
    def from_dict(cls, dikt) -> 'GetCidSetFileResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetCidSetFileResponse of this GetCidSetFileResponse.  # noqa: E501
        :rtype: GetCidSetFileResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this GetCidSetFileResponse.


        :return: The signature of this GetCidSetFileResponse.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this GetCidSetFileResponse.


        :param signature: The signature of this GetCidSetFileResponse.
        :type signature: object
        """

        self._signature = signature

    @property
    def cid_set_file(self) -> CreateCidSetFileResponsepropertiesCidSetFile:
        """Gets the cid_set_file of this GetCidSetFileResponse.


        :return: The cid_set_file of this GetCidSetFileResponse.
        :rtype: CreateCidSetFileResponsepropertiesCidSetFile
        """
        return self._cid_set_file

    @cid_set_file.setter
    def cid_set_file(self, cid_set_file: CreateCidSetFileResponsepropertiesCidSetFile):
        """Sets the cid_set_file of this GetCidSetFileResponse.


        :param cid_set_file: The cid_set_file of this GetCidSetFileResponse.
        :type cid_set_file: CreateCidSetFileResponsepropertiesCidSetFile
        """

        self._cid_set_file = cid_set_file
