# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cid_set_eventproperties_cid import CidSetEventpropertiesCid  # noqa: F401,E501
from swagger_server.models.object import Object  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class GetEntryByCidResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, cid: CidSetEventpropertiesCid=None, entry: AllOfGetEntryByCidResponseEntry=None):  # noqa: E501
        """GetEntryByCidResponse - a model defined in Swagger

        :param signature: The signature of this GetEntryByCidResponse.  # noqa: E501
        :type signature: object
        :param cid: The cid of this GetEntryByCidResponse.  # noqa: E501
        :type cid: CidSetEventpropertiesCid
        :param entry: The entry of this GetEntryByCidResponse.  # noqa: E501
        :type entry: AllOfGetEntryByCidResponseEntry
        """
        self.swagger_types = {
            'signature': object,
            'cid': CidSetEventpropertiesCid,
            'entry': AllOfGetEntryByCidResponseEntry
        }

        self.attribute_map = {
            'signature': 'Signature',
            'cid': 'Cid',
            'entry': 'Entry'
        }
        self._signature = signature
        self._cid = cid
        self._entry = entry

    @classmethod
    def from_dict(cls, dikt) -> 'GetEntryByCidResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetEntryByCidResponse of this GetEntryByCidResponse.  # noqa: E501
        :rtype: GetEntryByCidResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this GetEntryByCidResponse.


        :return: The signature of this GetEntryByCidResponse.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this GetEntryByCidResponse.


        :param signature: The signature of this GetEntryByCidResponse.
        :type signature: object
        """

        self._signature = signature

    @property
    def cid(self) -> CidSetEventpropertiesCid:
        """Gets the cid of this GetEntryByCidResponse.


        :return: The cid of this GetEntryByCidResponse.
        :rtype: CidSetEventpropertiesCid
        """
        return self._cid

    @cid.setter
    def cid(self, cid: CidSetEventpropertiesCid):
        """Sets the cid of this GetEntryByCidResponse.


        :param cid: The cid of this GetEntryByCidResponse.
        :type cid: CidSetEventpropertiesCid
        """
        if cid is None:
            raise ValueError("Invalid value for `cid`, must not be `None`")  # noqa: E501

        self._cid = cid

    @property
    def entry(self) -> AllOfGetEntryByCidResponseEntry:
        """Gets the entry of this GetEntryByCidResponse.


        :return: The entry of this GetEntryByCidResponse.
        :rtype: AllOfGetEntryByCidResponseEntry
        """
        return self._entry

    @entry.setter
    def entry(self, entry: AllOfGetEntryByCidResponseEntry):
        """Sets the entry of this GetEntryByCidResponse.


        :param entry: The entry of this GetEntryByCidResponse.
        :type entry: AllOfGetEntryByCidResponseEntry
        """
        if entry is None:
            raise ValueError("Invalid value for `entry`, must not be `None`")  # noqa: E501

        self._entry = entry
