# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.get_entry_by_cid_responseproperties_entry import GetEntryByCidResponsepropertiesEntry  # noqa: F401,E501
from swagger_server.models.get_entry_response_statistics import GetEntryResponseStatistics  # noqa: F401,E501
from swagger_server import util


class GetEntryResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, entry: GetEntryByCidResponsepropertiesEntry=None, statistics: GetEntryResponseStatistics=None):  # noqa: E501
        """GetEntryResponse - a model defined in Swagger

        :param signature: The signature of this GetEntryResponse.  # noqa: E501
        :type signature: object
        :param entry: The entry of this GetEntryResponse.  # noqa: E501
        :type entry: GetEntryByCidResponsepropertiesEntry
        :param statistics: The statistics of this GetEntryResponse.  # noqa: E501
        :type statistics: GetEntryResponseStatistics
        """
        self.swagger_types = {
            'signature': object,
            'entry': GetEntryByCidResponsepropertiesEntry,
            'statistics': GetEntryResponseStatistics
        }

        self.attribute_map = {
            'signature': 'Signature',
            'entry': 'Entry',
            'statistics': 'Statistics'
        }
        self._signature = signature
        self._entry = entry
        self._statistics = statistics

    @classmethod
    def from_dict(cls, dikt) -> 'GetEntryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GetEntryResponse of this GetEntryResponse.  # noqa: E501
        :rtype: GetEntryResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this GetEntryResponse.


        :return: The signature of this GetEntryResponse.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this GetEntryResponse.


        :param signature: The signature of this GetEntryResponse.
        :type signature: object
        """

        self._signature = signature

    @property
    def entry(self) -> GetEntryByCidResponsepropertiesEntry:
        """Gets the entry of this GetEntryResponse.


        :return: The entry of this GetEntryResponse.
        :rtype: GetEntryByCidResponsepropertiesEntry
        """
        return self._entry

    @entry.setter
    def entry(self, entry: GetEntryByCidResponsepropertiesEntry):
        """Sets the entry of this GetEntryResponse.


        :param entry: The entry of this GetEntryResponse.
        :type entry: GetEntryByCidResponsepropertiesEntry
        """
        if entry is None:
            raise ValueError("Invalid value for `entry`, must not be `None`")  # noqa: E501

        self._entry = entry

    @property
    def statistics(self) -> GetEntryResponseStatistics:
        """Gets the statistics of this GetEntryResponse.


        :return: The statistics of this GetEntryResponse.
        :rtype: GetEntryResponseStatistics
        """
        return self._statistics

    @statistics.setter
    def statistics(self, statistics: GetEntryResponseStatistics):
        """Sets the statistics of this GetEntryResponse.


        :param statistics: The statistics of this GetEntryResponse.
        :type statistics: GetEntryResponseStatistics
        """
        if statistics is None:
            raise ValueError("Invalid value for `statistics`, must not be `None`")  # noqa: E501

        self._statistics = statistics
