# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.problem_violations import ProblemViolations  # noqa: F401,E501
from swagger_server import util


class InlineResponse404(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, title: str=None, status: int=None, detail: str=None, correlation_id: str=None, violations: List[ProblemViolations]=None):  # noqa: E501
        """InlineResponse404 - a model defined in Swagger

        :param type: The type of this InlineResponse404.  # noqa: E501
        :type type: str
        :param title: The title of this InlineResponse404.  # noqa: E501
        :type title: str
        :param status: The status of this InlineResponse404.  # noqa: E501
        :type status: int
        :param detail: The detail of this InlineResponse404.  # noqa: E501
        :type detail: str
        :param correlation_id: The correlation_id of this InlineResponse404.  # noqa: E501
        :type correlation_id: str
        :param violations: The violations of this InlineResponse404.  # noqa: E501
        :type violations: List[ProblemViolations]
        """
        self.swagger_types = {
            'type': str,
            'title': str,
            'status': int,
            'detail': str,
            'correlation_id': str,
            'violations': List[ProblemViolations]
        }

        self.attribute_map = {
            'type': 'type',
            'title': 'title',
            'status': 'status',
            'detail': 'detail',
            'correlation_id': 'correlationId',
            'violations': 'violations'
        }
        self._type = type
        self._title = title
        self._status = status
        self._detail = detail
        self._correlation_id = correlation_id
        self._violations = violations

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse404':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_404 of this InlineResponse404.  # noqa: E501
        :rtype: InlineResponse404
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this InlineResponse404.


        :return: The type of this InlineResponse404.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this InlineResponse404.


        :param type: The type of this InlineResponse404.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def title(self) -> str:
        """Gets the title of this InlineResponse404.


        :return: The title of this InlineResponse404.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this InlineResponse404.


        :param title: The title of this InlineResponse404.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def status(self) -> int:
        """Gets the status of this InlineResponse404.


        :return: The status of this InlineResponse404.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this InlineResponse404.


        :param status: The status of this InlineResponse404.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def detail(self) -> str:
        """Gets the detail of this InlineResponse404.


        :return: The detail of this InlineResponse404.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail: str):
        """Sets the detail of this InlineResponse404.


        :param detail: The detail of this InlineResponse404.
        :type detail: str
        """

        self._detail = detail

    @property
    def correlation_id(self) -> str:
        """Gets the correlation_id of this InlineResponse404.

        Identificador de correlação do problema para fins de suporte  # noqa: E501

        :return: The correlation_id of this InlineResponse404.
        :rtype: str
        """
        return self._correlation_id

    @correlation_id.setter
    def correlation_id(self, correlation_id: str):
        """Sets the correlation_id of this InlineResponse404.

        Identificador de correlação do problema para fins de suporte  # noqa: E501

        :param correlation_id: The correlation_id of this InlineResponse404.
        :type correlation_id: str
        """

        self._correlation_id = correlation_id

    @property
    def violations(self) -> List[ProblemViolations]:
        """Gets the violations of this InlineResponse404.


        :return: The violations of this InlineResponse404.
        :rtype: List[ProblemViolations]
        """
        return self._violations

    @violations.setter
    def violations(self, violations: List[ProblemViolations]):
        """Sets the violations of this InlineResponse404.


        :param violations: The violations of this InlineResponse404.
        :type violations: List[ProblemViolations]
        """

        self._violations = violations
