# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.create_dispute_responseproperties_dispute import CreateDisputeResponsepropertiesDispute  # noqa: F401,E501
from swagger_server import util


class ListDisputesResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, signature: object=None, has_more_elements: bool=None, disputes: List[CreateDisputeResponsepropertiesDispute]=None):  # noqa: E501
        """ListDisputesResponse - a model defined in Swagger

        :param signature: The signature of this ListDisputesResponse.  # noqa: E501
        :type signature: object
        :param has_more_elements: The has_more_elements of this ListDisputesResponse.  # noqa: E501
        :type has_more_elements: bool
        :param disputes: The disputes of this ListDisputesResponse.  # noqa: E501
        :type disputes: List[CreateDisputeResponsepropertiesDispute]
        """
        self.swagger_types = {
            'signature': object,
            'has_more_elements': bool,
            'disputes': List[CreateDisputeResponsepropertiesDispute]
        }

        self.attribute_map = {
            'signature': 'Signature',
            'has_more_elements': 'HasMoreElements',
            'disputes': 'Disputes'
        }
        self._signature = signature
        self._has_more_elements = has_more_elements
        self._disputes = disputes

    @classmethod
    def from_dict(cls, dikt) -> 'ListDisputesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ListDisputesResponse of this ListDisputesResponse.  # noqa: E501
        :rtype: ListDisputesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def signature(self) -> object:
        """Gets the signature of this ListDisputesResponse.


        :return: The signature of this ListDisputesResponse.
        :rtype: object
        """
        return self._signature

    @signature.setter
    def signature(self, signature: object):
        """Sets the signature of this ListDisputesResponse.


        :param signature: The signature of this ListDisputesResponse.
        :type signature: object
        """

        self._signature = signature

    @property
    def has_more_elements(self) -> bool:
        """Gets the has_more_elements of this ListDisputesResponse.

        Existem mais elementos para iterar  # noqa: E501

        :return: The has_more_elements of this ListDisputesResponse.
        :rtype: bool
        """
        return self._has_more_elements

    @has_more_elements.setter
    def has_more_elements(self, has_more_elements: bool):
        """Sets the has_more_elements of this ListDisputesResponse.

        Existem mais elementos para iterar  # noqa: E501

        :param has_more_elements: The has_more_elements of this ListDisputesResponse.
        :type has_more_elements: bool
        """

        self._has_more_elements = has_more_elements

    @property
    def disputes(self) -> List[CreateDisputeResponsepropertiesDispute]:
        """Gets the disputes of this ListDisputesResponse.


        :return: The disputes of this ListDisputesResponse.
        :rtype: List[CreateDisputeResponsepropertiesDispute]
        """
        return self._disputes

    @disputes.setter
    def disputes(self, disputes: List[CreateDisputeResponsepropertiesDispute]):
        """Sets the disputes of this ListDisputesResponse.


        :param disputes: The disputes of this ListDisputesResponse.
        :type disputes: List[CreateDisputeResponsepropertiesDispute]
        """

        self._disputes = disputes
