# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Violation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, reason: str=None, value: str=None, _property: str=None):  # noqa: E501
        """Violation - a model defined in Swagger

        :param reason: The reason of this Violation.  # noqa: E501
        :type reason: str
        :param value: The value of this Violation.  # noqa: E501
        :type value: str
        :param _property: The _property of this Violation.  # noqa: E501
        :type _property: str
        """
        self.swagger_types = {
            'reason': str,
            'value': str,
            '_property': str
        }

        self.attribute_map = {
            'reason': 'reason',
            'value': 'value',
            '_property': 'property'
        }
        self._reason = reason
        self._value = value
        self.__property = _property

    @classmethod
    def from_dict(cls, dikt) -> 'Violation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Violation of this Violation.  # noqa: E501
        :rtype: Violation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reason(self) -> str:
        """Gets the reason of this Violation.


        :return: The reason of this Violation.
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason: str):
        """Sets the reason of this Violation.


        :param reason: The reason of this Violation.
        :type reason: str
        """
        if reason is None:
            raise ValueError("Invalid value for `reason`, must not be `None`")  # noqa: E501

        self._reason = reason

    @property
    def value(self) -> str:
        """Gets the value of this Violation.


        :return: The value of this Violation.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value: str):
        """Sets the value of this Violation.


        :param value: The value of this Violation.
        :type value: str
        """

        self._value = value

    @property
    def _property(self) -> str:
        """Gets the _property of this Violation.


        :return: The _property of this Violation.
        :rtype: str
        """
        return self.__property

    @_property.setter
    def _property(self, _property: str):
        """Sets the _property of this Violation.


        :param _property: The _property of this Violation.
        :type _property: str
        """

        self.__property = _property
